# Xcode
# Build, test, and archive an Xcode workspace on macOS.
# Add steps that install certificates, test, sign, and distribute an app, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/xcode

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:
- script: /usr/local/bin/pod install --project-directory=swift
  displayName: 'pod install using a script'

- task: Xcode@5
  inputs:
    actions: 'build'
    scheme: 'ios-shoppe-demo'
    sdk: 'iphoneos'
    packageApp: true
    configuration: 'Debug'
    xcWorkspacePath: '**/*.xcodeproj'
    xcodeVersion: 'default' # Options: 10
